### ISSUE TITLE
question about using DiamondStorage

### ISSUE THREAD

**Issue by developer2346** [mudgen/diamond-governance-token#1]
Hi
according to  https://github.com/mudgen/governance-token-diamond/blob/c862b3cbfc4cc7cb052e160097a6662dc0f3b605/contracts/lib/InternalFunctions.sol#L14-L15
Why you didn't load `ets` like `ERC20TokenStorage storage ets = erc20TokenStorage();` ?
instead you loaded it using assembly.

**Comment by mudgen** [comment]
Saving a bit of gas which isn't necessary but I do what I can if it is easy and simple.

**Comment by developer2346** [comment]
Got it. Thanks.
